object LogForm: TLogForm
  Left = 0
  Top = 0
  Caption = 'LogForm'
  ClientHeight = 300
  ClientWidth = 635
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object memo: TMemo
    Left = 0
    Top = 0
    Width = 635
    Height = 300
    Align = alClient
    ReadOnly = True
    TabOrder = 0
    ExplicitLeft = 176
    ExplicitTop = 152
    ExplicitWidth = 185
    ExplicitHeight = 89
  end
end
